// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoojbxdvdvbwibdkaper.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvb2pieGR2ZHZid2liZGthcGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjM5MzgsImV4cCI6MjA2MTQ5OTkzOH0.goflhN-7kpZYqlqtLbPucScTyYs_40nIqANQpk4Tjj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);